#!/bin/bash
source "$(dirname $0)/params.conf"
while [ $# -gt 0 ]
do
    case "$1" in
        --threshold)
            shift
            if [ $# -gt 0 ]; then
                threshold=$1
            else
                echo "No threshold specified"
            fi
            shift
            ;;
        --discount)
            shift
            if [ $# -gt 0 ]; then
                discount=$1
            else
                echo "No discount specified"
            fi
            shift
            ;;
        --epsilon)
            shift
            if [ $# -gt 0 ]; then
                epsilon=$1
            else
                echo "No epsilon specified"
            fi
            shift
            ;;
        --samples)
            shift
            if [ $# -gt 0 ]; then
                samples=$1
            else
                echo "No samples specified"
            fi
            shift
            ;;
        --bots-dir)
            shift
            if [ $# -gt 0 ]; then
                bots_dir=$1
            else
                echo "No bots-dir specified"
            fi
            shift
            ;;
        --samples-dir)
            shift
            if [ $# -gt 0 ]; then
                samples_dir=$1
            else
                echo "No samples-dir specified"
            fi
            shift
            ;;
        --duplication)
            shift
            if [ $# -gt 0 ]; then
                duplication=$1
            else
                echo "No duplication specified"
            fi
            shift
            ;;
        --bind1)
            shift
            if [ $# -gt 0 ]; then
                bind1=$1
                no_bind1=false
            else
                echo "No bind1 specified"
            fi
            shift
            ;;
        --bind2)
            shift
            if [ $# -gt 0 ]; then
                bind2=$1
                no_bind2=false
            else
                echo "No bind2 specified"
            fi
            shift
            ;;
        --no-bind1)
            shift
            no_bind1=true
            ;;
        --no-bind2)
            shift
            no_bind2=true
            ;;
        *)
            break
            ;;
    esac
done

echo "threshold=$threshold
discount=$discount
epsilon=$epsilon
samples=$samples
bots_dir=$bots_dir
samples_dir=$samples_dir
duplication=$duplication
bind1=$bind1
bind2=$bind2
no_bind1=$no_bind1
no_bind2=$no_bind2" > ./params.conf

data="actionThreshold=$threshold"
data="$data&discountFactor=$discount"
data="$data&epsilon=$epsilon"
data="$data&learningSamplesLimit=$samples"
data="$data&botsDirectory=$bots_dir"
data="$data&samplesDirectory=$samples_dir"
data="$data&allowBotDuplication=$duplication"
if [ "$no_bind1" == "false" ]; then
    data="$data&botBindingForPlayer1=$bind1"
fi
if [ "$no_bind2" == "false" ]; then
    data="$data&botBindingForPlayer2=$bind2"
fi

curl -s -X POST -d "$data" http://localhost:4321/admin/params
